### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Orcamm** [franckdpt/keep-my-monitors-awake#1]
Hi, wondering if you could create a Firefox extension which does the same thing? Thanks for this great extension!

**Comment by franckdpt** [comment]
Hi @Orcamm thank you for your feedback. I'll look into it this weekend 👍

**Comment by franckdpt** [comment]
Done. Instructions here: https://github.com/franckdpt/keep-my-monitors-awake/blob/master/README.md
